### ISSUE TITLE
Front-page example not functioning

### ISSUE THREAD

**Issue by ivan-krukov** [mariodeng/FirebrowseR#2]
The short "how to use it example" is returning `NULL`.
```
> mRNA.Exp = Samples.mRNASeq(gene = c("PTEN", "RUNX1"),
                           tcga_participant_barcode = c("TCGA-GF-A4EO",
                                                        "TCGA-AC-A2FG"))
> mRNA.Exp
NULL
```
Installed current master branch with `devtools::install_github`

**Comment by ivan-krukov** [comment]
This might have been a temporary issue with the API response. However, it would be nice to have a warning if `200` is returned.

**Comment by ivan-krukov** [comment]
I created a pull request https://github.com/mariodeng/FirebrowseR/pull/3. Notice that since the API returns are explicitly checked now, several tests fail. Beforehand they were erroneously passed.

**Comment by ranikay** [comment]
I'm getting a warning when running the code in the short "how to use" example.

`
devtools::install_github("mariodeng/FirebrowseR")
library(FirebrowseR)
mRNA.Exp = Samples.mRNASeq(gene = c("PTEN", "RUNX1"),
                                                       tcga_participant_barcode = c("TCGA-GF-A4EO",
                                                                                                      "TCGA-AC-A2FG"))

# Warning message:
# In download.Data(url, format, page) :
#        The API responded with code  504. Your query might be to big
`

Could this be a temporary issue with the API response? It seems odd that the query would actually be too big.

**Comment by mariodeng** [comment]
Hey Ranikay,

This should be a temporary issue with the API, for me the example is
working BUT:

Since yesterday the source code is generated automatically by a swagger
client and since now the default format is “json”. Therefor a list is
returned, not a data frame. To work around this issue, see the code below
(just specify the format to “tsv” or “csv”).

Nevertheless I need to work on the examples and vignettes. Thank you for
bringing this up.

devtools::install_github("mariodeng/FirebrowseR")

require(FirebrowseR)
mRNA.Exp = Samples.mRNASeq(gene = c("PTEN", "RUNX1"),
                           tcga_participant_barcode = c("TCGA-GF-A4EO",
                                                        "TCGA-AC-A2FG"),
                           format="tsv"
)
mRNA.Exp[, c("tcga_participant_barcode", "expression_log2", "z.score")]

2016-03-25 3:57 GMT+01:00 ranikay <notifications@github.com>:
